// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// GetAccountByID provides a mock function with given fields: accountID, _a1
func (_m *Reader) GetAccountByID(accountID string, _a1 interface{}) error {
	ret := _m.Called(accountID, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(accountID, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccountsByPrincipalID provides a mock function with given fields: principalID, accounts
func (_m *Reader) GetAccountsByPrincipalID(principalID string, accounts interface{}) error {
	ret := _m.Called(principalID, accounts)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(principalID, accounts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccountsByStatus provides a mock function with given fields: status, accounts
func (_m *Reader) GetAccountsByStatus(status string, accounts interface{}) error {
	ret := _m.Called(status, accounts)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(status, accounts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
